#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master

jobs:

  build_openwrt:

    name: Build OpenWrt
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/coolsnowwolf/lede@master
        with:
          ref: master

      - name: Space cleanup
        run: ls
